import json
import os
from pathlib import Path

import requests

BASE_DIR = Path(__file__).resolve().parent
APP_DIR = BASE_DIR.parent  # student-3Tristan-Lim/

DATABASE_SERVICE_URL = os.getenv("DATABASE_SERVICE_URL", "http://localhost:5103")
TIMEOUT = float(os.getenv("MCP_TOOL_TIMEOUT", "5"))

VALID_STATUSES = {"overloaded", "underloaded", "ok"}


def get_staff_count():
    """Total number of staff with a workload profile."""
    response = requests.get(
        f"{DATABASE_SERVICE_URL}/staff_workload_profile", timeout=TIMEOUT
    )
    response.raise_for_status()
    return {"staff_count": len(response.json())}


def get_staff_by_status(status: str):
    """Staff filtered by workload status: overloaded, underloaded, or ok."""
    normalised = (status or "").strip().lower()
    if normalised not in VALID_STATUSES:
        return {"error": f"status must be one of {sorted(VALID_STATUSES)}"}

    response = requests.get(
        f"{DATABASE_SERVICE_URL}/staff_workload_profile",
        params={"status": normalised},
        timeout=TIMEOUT,
    )
    response.raise_for_status()
    rows = response.json()
    return [
        {
            "staff_id": r["staff_id"],
            "staff_name": r["staff_name"],
            "department": r["department"],
            "current_total_hours": r["current_total_hours"],
            "max_weekly_hours": r["max_weekly_hours"],
            "status": r["status"],
        }
        for r in rows
    ]


def list_project_files(directory_path: str = ".."):
    """List files/folders in a directory, relative to mcp-server/."""
    path = (BASE_DIR / directory_path).resolve()
    if not path.exists() or not path.is_dir():
        return {"error": f"Directory not found: {path}"}

    return sorted(item.name for item in path.iterdir())


def read_ci_report(report_path: str = "../reports/report.json"):
    """Read the CI evidence report generated by student-3-TristanLim.yml."""
    report_file = (BASE_DIR / report_path).resolve()
    if not report_file.exists():
        return {
            "error": "Report not found",
            "path": str(report_file),
            "hint": "Run the student-3-TristanLim.yml workflow to generate report.json",
        }

    with report_file.open("r", encoding="utf-8") as file:
        return json.load(file)


if __name__ == "__main__":
    print(get_staff_count())
    print(get_staff_by_status("overloaded"))
    print(list_project_files(".."))
    print(read_ci_report("../reports/report.json"))
