FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY init_db.py .
COPY seed.py .

RUN python init_db.py
RUN python seed.py

CMD ["tail", "-f", "/dev/null"]