FROM nginx:alpine

COPY student-2Hein-Htet-Aung/frontend/index.html /usr/share/nginx/html/index.html
COPY student-2Hein-Htet-Aung/frontend/js/ /usr/share/nginx/html/js/
COPY ./shared/frontend/css/styles.css /usr/share/nginx/html/css/styles.css

EXPOSE 80